### ISSUE TITLE
Potential fixes in  a few spots

### ISSUE THREAD

**Issue by jhibbets** [open-organization-ambassadors/organize-for-innovation#1]
printed book page 33 - how to keep a meritocracy in check
2nd para "I remember vividly a conversation that..." I think needs a pause or rearrangement:
1) I remember vividly, a conversation that
2) I vividly remember a conversation that

page 50 - What the community taught me about open orgs
3rd para, last sentence "It talks about are things you're asking" - I think there is an unneeded "are" in the quote
1) It talks about things you're asking
2) All it talks about are things you're asking

page 65 - Why aren't we more invested in our work
last para - "and specifically how their work is**,**connected is connected to it -- has a comma instead of a space.

page 74 - Appreciating the full power of open
last para "And it's integral to openness because without it people don't have the knowledge" -- missing a comma:
And it's integral to openness because without it**,** people don't have the knowledge

**Comment by semioticrobotic** [comment]
Thanks again for these, @jhibbets. They've now been [incorporated into V1.2 of the book](https://github.com/open-organization-ambassadors/organize-for-innovation/commit/cb57190b890f442407f1b6ee612240904c5b8f8f), now in development.
